framework:
    secret: '%env(APP_SECRET)%'
    http_method_override: false
    session:
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    php_errors:
        log: true
    set_locale_from_accept_language: true
    set_content_language_from_locale: true
    default_locale: en
    enabled_locales: ['en']

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
