framework:
  workflows:
    payment:
      type: 'state_machine'
      marking_store:
        service: 'fms.marker'
      supports:
        - App\Domain\Model\Payment
      places:
        - new
        - token
        - awaiting
        - successfully
        - failure
        - timeout
        - unknown
      transitions:
        tokenized:
          from: new
          to: token
        registered:
          from: token
          to: awaiting
        complete:
          from: awaiting
          to: successfully
        failure:
          from: [new, token, awaiting]
          to: failure
        timeout:
          from: awaiting
          to: timeout
        unexpected:
          from: awaiting
          to: unknown
        expire:
          from: timeout
          to: failure
        alert:
          from: unknown
          to: failure
