framework:
  workflows:
    payment:
      type: 'state_machine'
      marking_store:
        service: 'fms.marker'
      supports:
        - App\Domain\Model\Payment
      places:
        new:
        awaiting:
        successfully:
        failure:
      transitions:
        register:
          from: new
          to: awaiting
        complete:
          from: awaiting
          to: successfully
        failure:
          from: [new, awaiting]
          to: failure
