api:
  resource: ../src/Presentation/API
  type: attribute
  prefix: /api

health:
  resource: ../src/Presentation/HealthCheck
  type: attribute
  prefix: /health


when@develop:
  web_profiler_wdt:
    resource: '@WebProfilerBundle/Resources/config/routing/wdt.xml'
    prefix: /_wdt

  web_profiler_profiler:
    resource: '@WebProfilerBundle/Resources/config/routing/profiler.xml'
    prefix: /_profiler
