services:
  _defaults:
    public: true

  App\Application\HealthCheck\Business\Checker\CheckerInterface:
    public: true

  App\Application\Gateway\Business\GatewayFacade:
    public: true
    arguments:
      $reader: '@App\Application\Gateway\Business\Reader\GatewayReader'
      $writer: '@App\Application\Gateway\Business\Writer\GatewayWriter'


  App\Application\Store\Business\StoreFacade:
    public: true
    arguments:
      $writer: '@App\Application\Store\Business\Writer\StoreWriter'
      $reader: '@App\Application\Store\Business\Reader\StoreReader'

  App\Application\User\Business\UserFacade:
    public: true
    arguments:
      $writer: '@App\Application\User\Business\Writer\UserWriter'
      $reader: '@App\Application\User\Business\Reader\UserReader'

  App\Application\Payment\Business\PaymentFacade:
    public: true
    arguments:
      $reader: '@App\Application\Payment\Business\Reader\PaymentReader'
      $processor: '@App\Application\Payment\Business\PaymentProcessor\PaymentProcessor'

  guzzle.handlers:
    class: GuzzleHttp\Handler\MockHandler
    arguments:
      $queue: []

  GuzzleHttp\Client:
    arguments:
      - { handler: '@guzzle.handlers' }
